### ISSUE TITLE
Messages are not displayed

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#163]
This is a strange issue, but one that I regularly have and I'm not entirely sure what's going on. I've been trying to determine whether this is a local issue or a problem with Cadence, but haven't made any interesting breakthroughs yet. Here's what I know.

Occasionally, when I log in, I get the following messages as normal:
(15:49:31) Ligrev: Automatically logging in as Neb
(15:49:31) Ligrev: Connecting ...
(15:49:33) Ligrev: You are now connected.
(15:49:33) Ligrev: Joining Ligrev's Lounge as Neb ...
(15:49:34) Ligrev: Now talking in Ligrev's Lounge.
(15:49:34) Ligrev: Neb logs into the Chat.

After this point, nothing else happens. Whether I say something, someone else says something, or I type /bans to get the chat itself to say something, nothing else displays on my end. That said, I can still speak and see updates to the conversation via the web-based chat log.

This issue will affect both Chrome (40.0.2214.111 m) and Firefox (35.0.1) at the same time, but NOT Internet Explorer (11.0.16).

So far, the only solution is to restart my entire computer. Hard refreshes etc. don't have an effect.

**Comment by Nebedia** [comment]
To clarify, I am able to see the last twenty backlog messages in the chat when I log in; however, I know I'm not going to be able to see any /new/ messages if I've I've said something within the last twenty messages and it's missing when I log back in.

**Comment by cburschka** [comment]
What happens to local commands like `/version`?

Also, do you see anything in the Java console when config.settings.debug is set to 1 and you say something?

**Comment by Nebedia** [comment]
I made a mistake in that post. I can get /ban messages and, presumably /version messages.
I will wait for the bug to occur again, but I'm having trouble getting Java to open and stay open. I will get help with it from Sy and get back to you.

**Comment by Nebedia** [comment]
https://gist.github.com/Nebedia/ba450436d9d69fc3017d
So, the first event is me typing "." which doesn't display for me. The second event is me using /version, which I do see the response for. The third event is Sylae sending a message and, although it appears in this debug info, doesn't display for me.

**Comment by cburschka** [comment]
I suspect this is confirmation:

> (2015-02-20 21:36:43) Nalyd: according to my chat, nobody's said anything since I logged in over a day ago.
> (2015-02-20 21:37:09) Nalyd: aaaaand i though that was kinda neat and pretty to just see ligrev marking the login/outs
> (2015-02-20 21:37:11) Nalyd: buuuuut
> (2015-02-20 21:37:16) Nalyd: now i see my chat is just broken

This seems pretty weird.

I'm not sure I'll make the Feb 28 milestone, but if I can fix this bug by then, I'll rush a 1.6.1 release.

**Comment by cburschka** [comment]
Okay, symptoms appear to be strictly limited to incoming messages (possibly including both groupchat and private messages, though it hasn't been reproduced with private messages as far as I can tell).

The messages are clearly received by strophe, and appear in the debug stream, but are not printed. This implies that the problem should be one of these:

1. Strophe doesn't trigger the message event handler.
2. The message event handler does not append the message.
3. The message appending function itself is broken.

However, all of these problems *should* be either permanent or fixed by logging out and logging back in.

**Comment by cburschka** [comment]
I also can't reproduce it in Firefox or Chromium, and it doesn't seem to be limited to a specific machine or a specific connection either.

**Comment by Nebedia** [comment]
"However, all of these problems should be either permanent or fixed by logging out and logging back in."
As far as I can tell, this seems to have worked with Nalyd. For me, when the error is occurring, all three web browsers will be affected. The last time it happened, two days ago, even IE with no ad-ons let me see the chat - when previously it did. 

It would be helpful to have a clearer picture about whether mine is a cadence issue or something else on my end. But it doesn't appear anything else is affected when I can't see the chat. Additionally, my previous theories about memory leaks, BOINC interference, and other explanations are continually being proven false. The issue will will have a chance to happen even if the loading the chat is the first thing my computer does when it starts up and BOINC isn't running.

**Comment by Nebedia** [comment]
So, I have some new information.

"I know I'm not going to be able to see any /new/ messages if I've I've said something within the last twenty messages and it's missing when I log back in."
This is either no longer true or not consistently true.

Additionally:
This appears to be related to this issue. Now, occasionally users do not display in the Online Users panel when logged in. Yesterday with Nalyd, and today with Actaeon. All chat activity (aside from missing users) acts as normal and I am able to talk to people who do not register on the side pannel. Like the tests we've done so far, slash commands to ligrev still display and are accurate, by which I mean /who shows these users as being online despite being missing from the side panel. However, if this issue is occurring and I log out of the chat, I will not be able to log in and see any non-chatbot activity.

Could this be a memory leak issue?

**Comment by Nebedia** [comment]
So, I've just determined that when I can't see my messages or incoming messages, I /will/ be able to see my PMs. (although not incoming PMs)

**Comment by cburschka** [comment]
Yeah, outgoing PMs get displayed independently of the server, because
unlike public messages the server doesn't reflect or acknowledge them. They
get displayed on the client side before sending, and they'd probably show
up even if they couldn't be delivered due to a network error.

**Comment by cburschka** [comment]
Today I briefly got a similar bug while working on #103 and changing some visual functions. It wasn't reproducible, and it affected *all* messages, not just those sent by users... but it simply dropped them without a JS error or interrupting XMPP traffic.

If it keeps happening, I'd be interested if you could try out http://ermarian.net/cadence-1.8/#lounge and check the debug output there.

**Comment by cburschka** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/1448001/7703032/e86567ae-fe34-11e4-9d93-937855d60fc7.png)

Yay! Maybe I can finally figure out what is happening.

**Comment by cburschka** [comment]
Hm. In this case, just a syntax error, but I do have some ideas on what might be causing it, if it happens again.

Expanding the condition to
 
```diff
         if (node != this.room.current)
+          var invite = $('x invite', stanza);
+          if (!resource && invite.length) {
+            var room = xmpp.room.available[node];
+            if (!room) xmpp.getRoomInfo(node, function(data) {
+              room = data;
+              xmpp.room.available[node] = data;
+            });
+            var reason = $('reason', invite).text();
+            ui.messageAddInfo(strings.info.inviteReceived[+!!reason], {
+              user: {jid: invite.attr('from')},
+              room: room,
+              reason: reason
+            });
+          }
           return true;
```

made it return all the time for messages from the MUC domain, because of the missing {} around the if block.

This is not what caused the issue before, but it might indicate that the node / xmpp.room.current value are mismatched for some other reason, so all in-room messages get discarded.

**Comment by sylae** [comment]
I'VE GOTTEN THE BUG.

At first I thought my connection was being wonky, so I just refreshed. When I refreshed and it was still wonky, I realized IT'S HAPPENING. So yeah, I guess it can strike at any time, not just at login.

First thing at the top of the console (after refresh): https://c312441.ssl.cf1.rackcdn.com/sylae/images/misc/860a0176087f1ee27409c013de34a1f3.png

Presence changes show up in the chat, but not chat messages of any sort including direct messages. Of note, I am getting a few 'not well-formed' errors from time to time: https://c312441.ssl.cf1.rackcdn.com/sylae/images/misc/71d4d364493e220cd72cc42d40563c7f.png

I will be leaving this browser session open and logged in, hopefully Aran can get with me after I get off work to nail this bug, once and for all.

**Comment by cburschka** [comment]
I HAVE THIS AGAIN

In this case, I do get message elements appended to the chat pane, but they're set to opacity 0 for some reason.

**Comment by sylae** [comment]
I'm not sure if it's anything new, but I found a way to give oneself something like this bug (maybe actually this bug? I dunno)

behold, https://gist.github.com/sylae/9566db2e3ade52e0ac16

**Comment by cburschka** [comment]
The problem with this bug is that it's really just a crash that can happen
for any reason.

This particular crash seems to generate a message with no nick for some
reason; I'll investigate.

**Comment by sylae** [comment]
Has anyone had this happen lately? I can't remember the last time I got this bug. @nebedia says he hasn't seen it in 'forever'...

**Comment by cburschka** [comment]
I suppose a lot of the crash opportunities are gone now that the code is a bit more robust, so whatever caused it could've just disappeared.

In 2.0, the error-handling is rewritten in a way that dumps JS errors onto the screen and (hopefully) avoids event handlers silently crashing. It's not complete, but once it is this shouldn't be an issue anymore.

Guess I'll tentatively close this for now.

**Comment by sylae** [comment]
Figured out a cause of this:

I was dinking around on Conversations on my phone, and discovered I could set a subject for the room. This caused both myself and at least one other user to get Messages are not Displayed.

Removing the subject via Pidgin (apparently I cannot do that on Conversations?) caused it to work on refresh

**Comment by cburschka** [comment]
I suspect a lot of the edge cases in the message handler (including subjects) should be fixed now, but I#ll test it when I get home.

**Comment by Nebedia** [comment]
Yeah, I donno what did it, but this issue came back yesterday with a vengeance. I don't think chat messages are working for anyone at the current time.

**Comment by cburschka** [comment]
I'm gonna make a wild guess and say sy's experiment with the subject is in
the backlog and crashes everybody who joins.

If I have time at the airport, I'll try to get a hotfix in so it stops
happening.

-csb

**Comment by sylae** [comment]
```
function bound ()  - error -  Error { 1 more… } str is nullstrophe.js:1966:21	Strophe.Handler.prototype.run https://cdn.calref.net/chat/js/lib/strophe.js:1966:21
	Strophe.Connection.prototype._dataRecv/< https://cdn.calref.net/chat/js/lib/strophe.js:3032:29
	Strophe.forEachChild https://cdn.calref.net/chat/js/lib/strophe.js:939:17
	Strophe.Connection.prototype._dataRecv https://cdn.calref.net/chat/js/lib/strophe.js:3020:9
	Strophe.Bosh.prototype._onRequestStateChange https://cdn.calref.net/chat/js/lib/strophe.js:4657:17
	Strophe.Request.prototype._newXHR https://cdn.calref.net/chat/js/lib/strophe.js:4146:34
	Strophe.Request https://cdn.calref.net/chat/js/lib/strophe.js:4087:16
	Strophe.Bosh.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:4560:17
	Strophe.Connection.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:3634:9
	Strophe.Bosh.prototype._send https://cdn.calref.net/chat/js/lib/strophe.js:4900:35
	Strophe.Connection.prototype.send https://cdn.calref.net/chat/js/lib/strophe.js:2575:9
	xmpp.joinRoom https://cdn.calref.net/chat/js/core/xmpp.js:328:5
	xmpp.joinExistingRoom/< https://cdn.calref.net/chat/js/core/xmpp.js:276:12
	xmpp.getRoomInfo/< https://cdn.calref.net/chat/js/core/xmpp.js:234:9
	Strophe.Connection.prototype.sendIQ/handler< https://cdn.calref.net/chat/js/lib/strophe.js:2653:21
	Strophe.Handler.prototype.run https://cdn.calref.net/chat/js/lib/strophe.js:1957:22
	Strophe.Connection.prototype._dataRecv/< https://cdn.calref.net/chat/js/lib/strophe.js:3032:29
	Strophe.forEachChild https://cdn.calref.net/chat/js/lib/strophe.js:939:17
	Strophe.Connection.prototype._dataRecv https://cdn.calref.net/chat/js/lib/strophe.js:3020:9
	Strophe.Bosh.prototype._onRequestStateChange https://cdn.calref.net/chat/js/lib/strophe.js:4657:17
	(Async: EventHandlerNonNull)
	Strophe.Request.prototype._newXHR https://cdn.calref.net/chat/js/lib/strophe.js:4146:34
	Strophe.Request https://cdn.calref.net/chat/js/lib/strophe.js:4087:16
	Strophe.Bosh.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:4560:17
	Strophe.Connection.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:3634:9
	Strophe.Bosh.prototype._send https://cdn.calref.net/chat/js/lib/strophe.js:4900:35
	Strophe.Connection.prototype.send https://cdn.calref.net/chat/js/lib/strophe.js:2575:9
	Strophe.Connection.prototype.sendIQ https://cdn.calref.net/chat/js/lib/strophe.js:2679:9
	xmpp.getRoomInfo https://cdn.calref.net/chat/js/core/xmpp.js:230:5
	xmpp.joinExistingRoom https://cdn.calref.net/chat/js/core/xmpp.js:261:5
	chat.commands.join/join https://cdn.calref.net/chat/js/core/chat.js:397:9
	chat.commands.join https://cdn.calref.net/chat/js/core/chat.js:402:17
	xmpp.eventConnectCallback/< https://cdn.calref.net/chat/js/core/xmpp.js:1103:28
	xmpp.discoverRooms/< https://cdn.calref.net/chat/js/core/xmpp.js:644:23
	Strophe.Connection.prototype.sendIQ/handler< https://cdn.calref.net/chat/js/lib/strophe.js:2653:21
	Strophe.Handler.prototype.run https://cdn.calref.net/chat/js/lib/strophe.js:1957:22
	Strophe.Connection.prototype._dataRecv/< https://cdn.calref.net/chat/js/lib/strophe.js:3032:29
	Strophe.forEachChild https://cdn.calref.net/chat/js/lib/strophe.js:939:17
	Strophe.Connection.prototype._dataRecv https://cdn.calref.net/chat/js/lib/strophe.js:3020:9
	Strophe.Bosh.prototype._onRequestStateChange https://cdn.calref.net/chat/js/lib/strophe.js:4657:17
	(Async: EventHandlerNonNull)
	Strophe.Request.prototype._newXHR https://cdn.calref.net/chat/js/lib/strophe.js:4146:34
	Strophe.Request https://cdn.calref.net/chat/js/lib/strophe.js:4087:16
	Strophe.Bosh.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:4560:17
	Strophe.Connection.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:3634:9
	Strophe.Bosh.prototype._send https://cdn.calref.net/chat/js/lib/strophe.js:4900:35
	Strophe.Connection.prototype.send https://cdn.calref.net/chat/js/lib/strophe.js:2575:9
	Strophe.Connection.prototype.sendIQ https://cdn.calref.net/chat/js/lib/strophe.js:2679:9
	xmpp.discoverRooms https://cdn.calref.net/chat/js/core/xmpp.js:625:5
	xmpp.eventConnectCallback https://cdn.calref.net/chat/js/core/xmpp.js:1102:9
	Strophe.Connection.prototype._changeConnectStatus https://cdn.calref.net/chat/js/lib/strophe.js:2895:17
	Strophe.Connection.prototype._sasl_session_cb https://cdn.calref.net/chat/js/lib/strophe.js:3462:13
	Strophe.Handler.prototype.run https://cdn.calref.net/chat/js/lib/strophe.js:1957:22
	Strophe.Connection.prototype._dataRecv/< https://cdn.calref.net/chat/js/lib/strophe.js:3032:29
	Strophe.forEachChild https://cdn.calref.net/chat/js/lib/strophe.js:939:17
	Strophe.Connection.prototype._dataRecv https://cdn.calref.net/chat/js/lib/strophe.js:3020:9
	Strophe.Bosh.prototype._onRequestStateChange https://cdn.calref.net/chat/js/lib/strophe.js:4657:17
	(Async: EventHandlerNonNull)
	Strophe.Request.prototype._newXHR https://cdn.calref.net/chat/js/lib/strophe.js:4146:34
	Strophe.Request https://cdn.calref.net/chat/js/lib/strophe.js:4087:16
	Strophe.Bosh.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:4560:17
	Strophe.Connection.prototype._onIdle https://cdn.calref.net/chat/js/lib/strophe.js:3634:9
```

the "1 more" tells me this (cannot copy-paste for some reason):
![](https://cdn.calref.net/files.calref/16/4f12f797_dragSy.png)

The cutoff bit is:
```
"visual.lengthLimit@https://cdn.calref.net/chat/js/core/visual.js:437:5visual.format.nick@https://cdn.calref.net/chat/js/core/visual.js:154:14visual.format.user@https://cdn.calref.net/chat/js/core/visual.js:199:17visual.formatMessage@https://cdn.calref.net/chat/js/core/visual.js:84:37xmpp.eventMessageCallback@https://cdn.calref.net/chat/js/core/xmpp.js:1004:26Strophe.Handler.prototype.run@https://cdn.calref.net/chat/js/lib/strophe.js:1957:22Strophe.Connection.prototype._dataRecv/<@https://cdn.calref.net/chat/js/lib/strophe.js:3032:29Strophe.forEachChild@https://cdn.calref.net/chat/js/lib/strophe.js:939:17Strophe.Connection.prototype._dataRecv@https://cdn.calref.net/chat/js/lib/strophe.js:3020:9Strophe.Bosh.prototype._onRequestStateChange@https://cdn.calref.net/chat/js/lib/strophe.js:4657:17EventHandlerNonNull*Strophe.Request.prototype._newXHR@https://cdn.calref.net/chat/js/lib/strophe.js:4146:34Strophe.Request@https://cdn.calref.net/chat/js/lib/strophe.js:4087:16Strophe.Bosh.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:4560:17Strophe.Connection.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:3634:9setTimeout handler*Strophe.Bosh.prototype._send@https://cdn.calref.net/chat/js/lib/strophe.js:4900:35Strophe.Connection.prototype.send@https://cdn.calref.net/chat/js/lib/strophe.js:2575:9xmpp.joinRoom@https://cdn.calref.net/chat/js/core/xmpp.js:328:5xmpp.joinExistingRoom/<@https://cdn.calref.net/chat/js/core/xmpp.js:276:12xmpp.getRoomInfo/<@https://cdn.calref.net/chat/js/core/xmpp.js:234:9Strophe.Connection.prototype.sendIQ/handler<@https://cdn.calref.net/chat/js/lib/strophe.js:2653:21Strophe.Handler.prototype.run@https://cdn.calref.net/chat/js/lib/strophe.js:1957:22Strophe.Connection.prototype._dataRecv/<@https://cdn.calref.net/chat/js/lib/strophe.js:3032:29Strophe.forEachChild@https://cdn.calref.net/chat/js/lib/strophe.js:939:17Strophe.Connection.prototype._dataRecv@https://cdn.calref.net/chat/js/lib/strophe.js:3020:9Strophe.Bosh.prototype._onRequestStateChange@https://cdn.calref.net/chat/js/lib/strophe.js:4657:17EventHandlerNonNull*Strophe.Request.prototype._newXHR@https://cdn.calref.net/chat/js/lib/strophe.js:4146:34Strophe.Request@https://cdn.calref.net/chat/js/lib/strophe.js:4087:16Strophe.Bosh.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:4560:17Strophe.Connection.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:3634:9setTimeout handler*Strophe.Bosh.prototype._send@https://cdn.calref.net/chat/js/lib/strophe.js:4900:35Strophe.Connection.prototype.send@https://cdn.calref.net/chat/js/lib/strophe.js:2575:9Strophe.Connection.prototype.sendIQ@https://cdn.calref.net/chat/js/lib/strophe.js:2679:9xmpp.getRoomInfo@https://cdn.calref.net/chat/js/core/xmpp.js:230:5xmpp.joinExistingRoom@https://cdn.calref.net/chat/js/core/xmpp.js:261:5chat.commands.join/join@https://cdn.calref.net/chat/js/core/chat.js:397:9chat.commands.join@https://cdn.calref.net/chat/js/core/chat.js:402:17xmpp.eventConnectCallback/<@https://cdn.calref.net/chat/js/core/xmpp.js:1103:28xmpp.discoverRooms/<@https://cdn.calref.net/chat/js/core/xmpp.js:644:23Strophe.Connection.prototype.sendIQ/handler<@https://cdn.calref.net/chat/js/lib/strophe.js:2653:21Strophe.Handler.prototype.run@https://cdn.calref.net/chat/js/lib/strophe.js:1957:22Strophe.Connection.prototype._dataRecv/<@https://cdn.calref.net/chat/js/lib/strophe.js:3032:29Strophe.forEachChild@https://cdn.calref.net/chat/js/lib/strophe.js:939:17Strophe.Connection.prototype._dataRecv@https://cdn.calref.net/chat/js/lib/strophe.js:3020:9Strophe.Bosh.prototype._onRequestStateChange@https://cdn.calref.net/chat/js/lib/strophe.js:4657:17EventHandlerNonNull*Strophe.Request.prototype._newXHR@https://cdn.calref.net/chat/js/lib/strophe.js:4146:34Strophe.Request@https://cdn.calref.net/chat/js/lib/strophe.js:4087:16Strophe.Bosh.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:4560:17Strophe.Connection.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:3634:9setTimeout handler*Strophe.Bosh.prototype._send@https://cdn.calref.net/chat/js/lib/strophe.js:4900:35Strophe.Connection.prototype.send@https://cdn.calref.net/chat/js/lib/strophe.js:2575:9Strophe.Connection.prototype.sendIQ@https://cdn.calref.net/chat/js/lib/strophe.js:2679:9xmpp.discoverRooms@https://cdn.calref.net/chat/js/core/xmpp.js:625:5xmpp.eventConnectCallback@https://cdn.calref.net/chat/js/core/xmpp.js:1102:9Strophe.Connection.prototype._changeConnectStatus@https://cdn.calref.net/chat/js/lib/strophe.js:2895:17Strophe.Connection.prototype._sasl_session_cb@https://cdn.calref.net/chat/js/lib/strophe.js:3462:13Strophe.Handler.prototype.run@https://cdn.calref.net/chat/js/lib/strophe.js:1957:22Strophe.Connection.prototype._dataRecv/<@https://cdn.calref.net/chat/js/lib/strophe.js:3032:29Strophe.forEachChild@https://cdn.calref.net/chat/js/lib/strophe.js:939:17Strophe.Connection.prototype._dataRecv@https://cdn.calref.net/chat/js/lib/strophe.js:3020:9Strophe.Bosh.prototype._onRequestStateChange@https://cdn.calref.net/chat/js/lib/strophe.js:4657:17EventHandlerNonNull*Strophe.Request.prototype._newXHR@https://cdn.calref.net/chat/js/lib/strophe.js:4146:34Strophe.Request@https://cdn.calref.net/chat/js/lib/strophe.js:4087:16Strophe.Bosh.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:4560:17Strophe.Connection.prototype._onIdle@https://cdn.calref.net/chat/js/lib/strophe.js:3634:9"
```

**Comment by cburschka** [comment]
Sudden crazy thought: If previous crashes were also caused by a message in
the backlog (possibly browser-specific as well) that could explain why it
went away after you restarted which gave the message time to drop off the
log.
-csb

**Comment by sylae** [comment]
I have a possible fix on The Other Branch here: https://github.com/calref/cadence/pull/20

look fine to you to push?

**Comment by cburschka** [comment]
Okay, I'm back. Let's see...
